spring:
  profiles:
    active: dev-1001
  application:
    name: discover-services
#  security:
#    user:
#      name: root
#      password: root
# by default every Eureka Server is also an Eureka Client and requires (at least one) services URL to locate a peer.
eureka:
  datacenter: bizvanedc
  instance:
    hostname: localhost
  environment: dev
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
server:
  port: 1001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1002/eureka/
spring:
  profiles: dev-1001
---
server:
  port: 1002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
spring:
  profiles: dev-1002
