spring:
  redis:
    host: 192.168.1.50
    port: 6379
    password: cskit
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  data:
    mongodb:
      uri: "mongodb://192.168.1.51:27017/?AutoConnectRetry=true"
#logging:
#  config: classpath:basecontroller-local.xml
#  level:
#    com.cskit.basecontroller: debug