spring:
  swagger:
    show: true
  redis:
    host: 192.168.1.50
    port: 6379
    password: cskit
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0
  data:
    mongodb:
      uri: "mongodb://192.168.1.51:27017/?AutoConnectRetry=true"
    elasticsearch:
      cluster-name: my-esLearn
      cluster-nodes: 192.168.1.45:9300
      repositories:
        enabled: true
  kafka:
      producer:
        bootstrap-servers: "192.168.1.50:9092"
        key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
        value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
        batch-size: 16384
        buffer-memory: 33554432
        retries: 0
        acks: "1"
      consumer:
        bootstrap-servers: "192.168.1.50:9092"
        enable-auto-commit: false
        auto-offset-reset: "earliest"
        key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        session-timeout: 30000
        request-timeout: 40000
        heartbeat-interval: 29000ms
        max-partition-fetch-bytes: 524288
#logging:
#  config: classpath:basecontroller-local.xml
#  level:
#    com.cskit.basecontroller: debug