server:
  port: 3000
spring:
  application:
    name: gateway-services
#  security:
#    user:
#      name: root
#      password: root
#  boot:
#    admin:
#      discovery:
#        ignored-services: adminservice-services

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10