spring:
  application:
    name: admin-services
  security:
    user:
      name: root
      password: root
  boot.admin.client:
    url: http://localhost:9999
    username: root
    password: root
    instance:
      metadata:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}

server:
  port: 8083

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

