server:
  port: 2001
spring:
  swagger:
    showinfo: true
  profiles:
    active: basecontroller,commonutilslocal,log
  redis:
    database: 0
  application:
    name: controlplat-serviceimpl
#  security:
#    enabled: false
#    user:
#      name: root
#      password: root
  datasource:
    hikari:
      catalog:
    name: database
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://cskit-2018.mysql.polardb.rds.aliyuncs.com:3306/common_platform_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: cskit_2018
      password: SF_cskit20180613
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        allow: localhost
        url-pattern: /druid/*

  data:
    mongodb:
      database: "0"
  kafka:
    producer:
      client-id: "kafka-etl"
    consumer:
       group-id: "kafka-etl"
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
tenant:
  isEnabledTenantInterceptor: true
#eureka:
#  instance:
#    metadata-map:
#      lease-expiration-duration-in-seconds: 30
#      lease-renewal-interval-in-seconds: 10
#  client:
#    service-url:
#      defaultZone: http://47.97.50.134:8761/eureka/
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
logging:
  level:
    root: info
#  config: classpath:logback-local.xml
#  level:
#    com.cskit.userinfoservice.mapper: debug
cskit:
  trace:
    controller:
      enabled: true
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8080
    ### xxl-job executor address
    executor:
      appname: mktcenter
      ip:
      port: 9888
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken: